package com.unicauca.bookings.presentation;

import com.unicauca.bookings.access.BookingRepository;
import com.unicauca.clientproducthttpclient.domain.entities.Booking;
import com.unicauca.bookings.domain.services.BookingService;
import com.unicauca.clientproducthttpclient.domain.entities.User;

/**
 *
 * @author libardo
 */
public class GUIBookings extends javax.swing.JFrame {

    BookingService bookingService = new BookingService(new BookingRepository());

    /**
     * Creates new form GUIProducts
     */
    public GUIBookings() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNorth = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        Consultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Reservas del Gimnasio");

        jLabel1.setText("Id de reserva:");
        pnlNorth.add(jLabel1);

        txtId.setText("1");
        txtId.setMinimumSize(new java.awt.Dimension(100, 23));
        txtId.setPreferredSize(new java.awt.Dimension(100, 23));
        pnlNorth.add(txtId);

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        pnlNorth.add(Consultar);

        getContentPane().add(pnlNorth, java.awt.BorderLayout.PAGE_START);

        txtData.setColumns(20);
        txtData.setRows(5);
        jScrollPane1.setViewportView(txtData);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        txtData.setText("");
        if (txtId.getText().trim().equals("")) {
            txtData.append("Id requerido en la consulta.");
            return;
        }
        Booking booking = bookingService.findById(Integer.parseInt(txtId.getText()));

        if (booking == null) {

            txtData.append("Id no encontrado");
            return;
        }
        User user = booking.getUser();
        txtData.setText("");

        txtData.append("Id reserva:" + booking.getId() + "\n");
        txtData.append("User Id: " + booking.getUserId() + "\n");
        txtData.append("Clase: " + booking.getGymClass().getDescription() + "\n");
        txtData.append("Instructor: " + booking.getGymClass().getInstuctor().getName());
    }//GEN-LAST:event_ConsultarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIBookings inst = new GUIBookings();
                inst.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                inst.setSize(500, 400);
                inst.setLocationRelativeTo(null);
                inst.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlNorth;
    private javax.swing.JTextArea txtData;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

}
